### ISSUE TITLE
CS-Studio docbook should be hosted on controlsystemstudio.org

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/controlsystemstudio.github.com#30]
Shouldn't it?  I find it confusing that it is still hosted on the sourceforge site.

**Comment by kasemir** [comment]
I think the reason is that we can't serve plain content (generated html, pdf, ..) on github.
It was and is possible on source forge, so we left the content there while the source repo for the docbook of course moved to github.
As an alternative to source forge we may be able to use amazon S3, as we already do for the plugin binaries, but that's not a free service.

**Comment by willrogers** [comment]
I see.  It's just a little confusing.

**Comment by berryma4** [comment]
I have to make a new s3 bucket for releases (the tar files).  I could add the docbook bucket too.
